### ISSUE TITLE
[Feature]: Upgrade to window with rounded edges!

### ISSUE THREAD

**Issue by maisondasilva** [XFox111/PasswordGeneratorExtension#241]
### Proposed solution

```Markdown
Hello, is it possible to update Edge to a model with rounded edges
```

### Justification

```Markdown
Follow the same standard as Windows 11/New Edge
```

### Alternatives

```Markdown
Keep the current version!
```

### Are you willing to submit a PR for this issue?

no

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by XFox111** [comment]
Hi @maisondasilva. Yeah, that would've been great. Unfortunately I have no control over the popup shape - this is something the browser does. 

But in case it is something that I am able to do, I would be glad if you send me an example of extension that does so.

**Comment by maisondasilva** [comment]
@XFox111 I'll check with the Edge Dev Team and let you know.

**Comment by XFox111** [comment]
I'll close this issue for now, as there's no progress on it. Feel free to reopen it once there's new info available.
