### ISSUE TITLE
[Bug]: The link to source code is redirecting to a 404 page

### ISSUE THREAD

**Issue by maisondasilva** [XFox111/PasswordGeneratorExtension#242]
### Description

```Markdown
Open Source Code

https://github.com/xfox111/PasswordGeneratorExtensionundefined
```

### Reproduction steps

```Markdown
Open link Source Code
```

### Expected behavior

```Markdown
https://github.com/XFox111/PasswordGeneratorExtension/
```

### Operating system

Windows 10+

### Browser name and version

Versão 120.0.2210.22

### Extension version

3.0.0

![image](https://github.com/XFox111/PasswordGeneratorExtension/assets/11423362/5fce8712-339d-43bf-b475-7b01dc77c248)

### Are you willing to submit a PR for this issue?

yes

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a minimal reproducible example of the bug.

**Comment by maisondasilva** [comment]
Done

https://github.com/XFox111/PasswordGeneratorExtension/pull/243

**Comment by XFox111** [comment]
Hi @maisondasilva. I've merged the PR. Once the new release is ready, I will close this issue as well.
