### ISSUE TITLE
Extension is not doing anything

### ISSUE THREAD

**Issue by ebardet** [XFox111/PasswordGeneratorExtension#51]
### Description
I installed the extension on FirefoxDevelopper edition and while the button is available, it does not show much on click down.

### Reproduction steps
1. Installed 2.0.1 extension on FirefoxDevelopper 106.0b9
2. Click on "Key" button
3. An empty tooltip like window pops up against the button
4. Restarted Firefox
5. Same behavior

### Expected behavior
Expected same as screenshot [in ](https://addons.mozilla.org/user-media/previews/thumbs/272/272972.jpg?modified=1662641633)

### Screenshots
![image](https://user-images.githubusercontent.com/6052513/196138972-eb85ec24-2405-4e40-b6db-2a689b26fd95.png)

### Environment
Please provide the following information:
 - Operating System: MacOS latest
 - Browser: FirefoxDevelopper 106.0b9
 - Extension version: 2.0.1

### Additional context
NA

- [y] Are you willing to submit a pull request to implement this feature yourself? If directed.

**Comment by ebardet** [comment]
Hello @XFox111, Hérizo is not only faster but a lot more proficient than me :)

**Comment by ebardet** [comment]
For sure!  He was the man ;)

**Comment by XFox111** [comment]
I've created a new release. This issue should be fixed. You can download it from [GitHub Release](https://github.com/XFox111/PasswordGeneratorExtension/releases/tag/v2.0.2) and test it to make sure. Webstore submission is on the way
