### ISSUE TITLE
Add History Pass Generated

### ISSUE THREAD

**Issue by maisondasilva** [XFox111/PasswordGeneratorExtension#71]
Add History Pass Generated

**Comment by XFox111** [comment]
Hi, thanks for the suggestion.

Unfortunately, as much as this feature seems to be useful it also is very insecure as browser extensions doesn't have capabilities to safely store this information.

Although, if you have an idea on how to securely implement this, you can post it here and I reconsider my decision

P.S. Next time you open an issue, please use the template as it allows to make feature suggestions more structured and detailed

**Comment by maisondasilva** [comment]
@XFox111 I saw this feature in this old extension. Can you see how they store the passwords?

https://chrome.google.com/webstore/detail/strong-password-generator/emehklffcaphknhhfhadkjhpfapcbpco

**Comment by XFox111** [comment]
I've checked it out. Looks like they store it as plain text which isn't secure at all. In fact, they explicitly ask users to clear history regularly as it may result in a security leak

From all said, it is a bad idea to give users ability to voluntarily ignore security precautions

```js
if( localStorage['passwordHistory'] != undefined ) {
	historyItems = JSON.parse(localStorage['passwordHistory']);
			
	if( historyItems.length > 0 ) {
		for ( i = 0; i < historyItems.length; i++ ) {
			addToList( historyItems[i] );
		}
	}
}
```

<img width="193" alt="image" src="https://user-images.githubusercontent.com/28831743/202551696-556eb4c6-feec-4963-b78d-abe99bb8ef25.png">
